name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor
        run: flutter doctor

      - name: Check project
        run: python -m py_compile main.py

      - name: Build iOS
        run: |
          yes | flet build ipa --verbose

      - name: Show build output
        if: always()
        run: |
          pwd
          find . -name "*.app"
          find . -name "*.xcarchive"
          find . -name "*.ipa"

      - name: List build output
        run: |
          ls -R build
          find build -type f
      
      - name: Create unsigned IPA
        run: |
          mkdir Payload
          cp -R build/ipa/stat-tracker-for-it-council.xcarchive/Products/Applications/stat-tracker-for-it-council.app Payload/
          zip -qry StatTracker-unsigned.ipa Payload
      
      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: StatTracker-unsigned
          path: StatTracker-unsigned.ipa
