name: Build iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor
        run: flutter doctor

      - name: Check project
        run: python -m py_compile main.py

      - name: Build iOS
        run: |
          yes | flet build ipa --verbose

      - name: Show build output
        if: always()
        run: |
          pwd
          find . -name "*.app"
          find . -name "*.xcarchive"
          find . -name "*.ipa"

      - name: List build output
        run: |
          ls -R build
          find build -type f
      
      - name: Create unsigned IPA
        run: |
          APP=$(find build/ipa -name "*.app" | head -n 1)
      
          echo "Found app: $APP"
      
          mkdir Payload
          cp -R "$APP" Payload/
      
          cd Payload
          zip -qry ../Stat-Tracker-for-IT-Council-unsigned.ipa .
          cd ..
      
      - name: Verify IPA
        run: |
          ls -lh
          unzip -l Stat-Tracker-for-IT-Council-unsigned.ipa | head -20
      
      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: Stat-Tracker-for-IT-Council-unsigned
          path: Stat-Tracker-for-IT-Council-unsigned.ipa
