name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flet
        run: |
          python -m pip install --upgrade pip
          pip install flet>=0.28.3

      - name: Verify project
        run: |
          python -m py_compile main.py

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.7"
      
      - name: Verify Flutter
        run: flutter doctor
      
      - name: Build iOS app
        run: |
          flet build ipa --verbose --yes

      - name: Build iOS app
        run: |
          flet build ipa --no-codesign]
      - name: Show build output
        run: |
          find build -maxdepth 5

      - name: Create unsigned IPA
        run: |
          mkdir Payload
          cp -R build/ipa/*.app Payload/
          cd .
          zip -r StatTracker-unsigned.ipa Payload
      
      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: StatTracker-unsigned
          path: StatTracker-unsigned.ipa
